mysql:
  engine: mariadb
  host: localhost
  port: 3306
  user: root
  password: minecraft
  database: Minecraft
  enable-ssl: false
  pool:
    max-pool-size: 10
    connection-timeout: 25
    max-lifetime: 1800
servername: Vestlandet
filter:
  blacklist: true
  wordfilter:
  - test
tilkoblinger:
  litebans:
    enable: true
    type:
      ban: true
      kick: false
      mute: false
      warn: false
  cmi:
    enable: true
    type:
      ban: true